apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-3
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/data/pv-3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-2
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv-2
# ReadWriteOnce – том может быть смонтирован на чтение и запись к одному поду.
# ReadOnlyMany – том может быть смонтирован на много подов в режиме только чтения.
# ReadWriteMany – том может быть смонтирован к множеству подов в режиме чтения и записи.