apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "wp_mysql.fullname" . }}-pv-3
  labels:
     {{- include "wp_mysql.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote}}
  accessModes:
    - {{ .Values.persistence.accessMode | quote}}
  hostPath:
    path: /tmp/data/pv-3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "wp_mysql.fullname" . }}-pv-2
  labels:
     {{- include "wp_mysql.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote}}
  accessModes:
    - {{ .Values.persistence.accessMode | quote}}
  hostPath:
    path: /tmp/data/pv-2
# ReadWriteOnce – том может быть смонтирован на чтение и запись к одному поду.
# ReadOnlyMany – том может быть смонтирован на много подов в режиме только чтения.
# ReadWriteMany – том может быть смонтирован к множеству подов в режиме чтения и записи.