apiVersion: v1
kind: Service
metadata:
  name: {{ include "wpmysql.fullname" . }}
  labels:
     {{- include "wpmysql.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.serviceWP.port }}
  selector: {{- include "wpmysql.selectorLabels" . | nindent 4 }}
  type: {{ .Values.serviceWP.type }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wpmysql.fullname" . }}-pvc
  labels:
     {{- include "wpmysql.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote}}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wpmysql.fullname" . }}
  labels:
     {{- include "wpmysql.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
     {{- include "wpmysql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
     {{- include "wpmysql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: "wordpress:{{ .Values.imageTagWP}}"
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          value: password
#          valueFrom: 
#             secretKeyRef:
#                 name: mysql-secret
#                 key: mysql-root-password
        resources: 
{{ toYaml .Values.resources | indent 10}}
        ports:
        - containerPort: {{ .Values.serviceWP.port }}
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "wpmysql.fullname" . }}-pvc
