apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wp_mysql.fullname" . }}
  labels:
     {{- include "wp_mysql.labels" . | nindent 4 }}
type: Opaque
data:
   mysql-root-password: cGFzc3dvcmQ=
